version: '3'
services:
  client:
    build: ./client
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/usr/src"
  db: 
    build: ./db
    ports:
      - "6001:5432"
  server:
    build: ./server
    expose: 
      - "3001"
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - "./server:/usr/src"